dbt_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: adminadmin
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
      connect_timeout: 30
